[project]
name = "that-game"
version = "0.0.1"
description = "Add your description here"
authors = [
    { name = "tanzhijian", email = "tanzhijianorg@outlook.com" }
]
dependencies = [
    "polars>=1.33.1",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.13.0",
    "mypy>=1.18.1",
    "pytest>=8.4.2",
    "ipykernel>=6.30.1",
    "nbformat>=5.10.4",
    "anywidget>=0.9.18",
    "soccer-viz @ git+https://github.com/tanzhijian/soccer-viz",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/that_game"]

[tool.ruff]
lint.select = ["E", "F", "I"]
line-length = 79

[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.pytest.ini_options]
testpaths = ["tests",]

[tool.pyright]
venvPath = "."
venv = ".venv"
